// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "providerSelectionVersion": number;
      "providerAutomatic": boolean;
      "providerCrossrefEnabled": boolean;
      "providerSemanticScholarEnabled": boolean;
      "providerOpenCitationsEnabled": boolean;
      "providerInspireEnabled": boolean;
      "providerOpenAlexEnabled": boolean;
      "openAlexAPIKey": string;
      "semanticScholarAPIKey": string;
      "showMetricTooltips": boolean;
      "automaticUpdates": boolean;
      "updateNewItems": boolean;
      "updateModifiedItems": boolean;
      "checkStaleOnStartup": boolean;
      "startupLibraryIDs": string;
      "startupLibrarySelectionVersion": number;
      "updateLibraryIDs": string;
      "updateLibrarySelectionVersion": number;
      "cacheDays": number;
      "exactTitleFallback": boolean;
      "localRelations": boolean;
      "noteExtraction": boolean;
      "pdfExtraction": boolean;
      "debugLogging": boolean;
      "detailPanelWidth": number;
      "detailPanelCollapsed": boolean;
      "graphAppearance": string;
      "graphAppearanceVersion": number;
    };
  }
}
