// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "openAlexAPIKey": string;
      "automaticUpdates": boolean;
      "updateNewItems": boolean;
      "cacheDays": number;
      "exactTitleFallback": boolean;
      "localRelations": boolean;
      "noteExtraction": boolean;
      "pdfExtraction": boolean;
      "debugLogging": boolean;
      "detailPanelWidth": number;
      "detailPanelCollapsed": boolean;
      "graphAppearance": string;
      "graphAppearanceVersion": number;
    };
  }
}
